wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: Scratch
dataset:
  desc: null
  value: de,en
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712986019.0
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.16.6
      6: 4.39.3
      8:
      - 1
      - 5
      13: linux-x86_64
